# Generated by Django 4.2.11 on 2024-12-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_answerkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKeyS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('answer_key_file', models.FileField(upload_to='answer_keys/')),
            ],
        ),
    ]
