# Generated by Django 4.2.11 on 2025-01-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_answerkeys_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerkeys',
            name='student',
            field=models.CharField(max_length=255),
        ),
    ]
